# Utiliser la dernière version d'Ubuntu comme image de base
FROM ubuntu:latest

# Mettre à jour et mettre à niveau APT
RUN apt-get update && apt-get upgrade -y

# Commande exécutée à chaque lancement du conteneur
CMD echo "Hello, World!"
